from flask import Flask , request
import requests , json , random

app = Flask(__name__)
app.config['JSON_AS_ASCII'] = False

@app.route('/',methods=["GET"])
def return_class():
    data = '''
        {
            "code": 0,
            "msg": "success",
            "data": [
                {
                    "id": 1439348,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "大学英语",
                    "abbr": "",
                    "week": 1,
                    "start_jie": 3,
                    "end_jie": 4,
                    "start_week": 2,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "王发启",
                    "for_class": "",
                    "address": "天工南107",
                    "remark": ""
                },
                {
                    "id": 1439322,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "离散数学2",
                    "abbr": "",
                    "week": 5,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 2,
                    "end_week": 9,
                    "week_type": 0,
                    "teacher": "李强",
                    "for_class": "",
                    "address": "天工南214",
                    "remark": ""
                },
                {
                    "id": 1439338,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 1,
                    "start_jie": 7,
                    "end_jie": 8,
                    "start_week": 2,
                    "end_week": 14,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439327,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "线性代数",
                    "abbr": "",
                    "week": 5,
                    "start_jie": 3,
                    "end_jie": 4,
                    "start_week": 2,
                    "end_week": 11,
                    "week_type": 0,
                    "teacher": "倪晋波",
                    "for_class": "",
                    "address": "明理103",
                    "remark": ""
                },
                {
                    "id": 1439323,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "离散数学2",
                    "abbr": "",
                    "week": 2,
                    "start_jie": 1,
                    "end_jie": 2,
                    "start_week": 2,
                    "end_week": 9,
                    "week_type": 0,
                    "teacher": "李强",
                    "for_class": "",
                    "address": "天工南314",
                    "remark": ""
                },
                {
                    "id": 1439345,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "数据结构",
                    "abbr": "",
                    "week": 4,
                    "start_jie": 3,
                    "end_jie": 4,
                    "start_week": 2,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "张明伟",
                    "for_class": "",
                    "address": "天工南406",
                    "remark": ""
                },
                {
                    "id": 1439346,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "数据结构",
                    "abbr": "",
                    "week": 2,
                    "start_jie": 3,
                    "end_jie": 4,
                    "start_week": 2,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "张明伟",
                    "for_class": "",
                    "address": "天工南406",
                    "remark": ""
                },
                {
                    "id": 1439347,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "大学英语",
                    "abbr": "",
                    "week": 4,
                    "start_jie": 1,
                    "end_jie": 2,
                    "start_week": 2,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "王发启",
                    "for_class": "",
                    "address": "天工南107",
                    "remark": ""
                },
                {
                    "id": 1439328,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "线性代数",
                    "abbr": "",
                    "week": 2,
                    "start_jie": 7,
                    "end_jie": 8,
                    "start_week": 2,
                    "end_week": 11,
                    "week_type": 0,
                    "teacher": "倪晋波",
                    "for_class": "",
                    "address": "明理103",
                    "remark": ""
                },
                {
                    "id": 1439330,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "大学物理Ⅰ（下）",
                    "abbr": "",
                    "week": 1,
                    "start_jie": 1,
                    "end_jie": 2,
                    "start_week": 2,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "曲忠伟",
                    "for_class": "",
                    "address": "天工南103",
                    "remark": ""
                },
                {
                    "id": 1439329,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "大学物理Ⅰ（下）",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 3,
                    "end_jie": 4,
                    "start_week": 2,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "曲忠伟",
                    "for_class": "",
                    "address": "天工南103",
                    "remark": ""
                },
                {
                    "id": 1439339,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 3,
                    "end_week": 3,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439340,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 5,
                    "end_week": 5,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439341,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 7,
                    "end_week": 7,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439342,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 9,
                    "end_week": 9,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439349,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "形势与政策",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 10,
                    "end_jie": 11,
                    "start_week": 10,
                    "end_week": 14,
                    "week_type": 0,
                    "teacher": "杨帆",
                    "for_class": "",
                    "address": "天工103",
                    "remark": ""
                },
                {
                    "id": 1439337,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "数字逻辑",
                    "abbr": "",
                    "week": 2,
                    "start_jie": 1,
                    "end_jie": 2,
                    "start_week": 10,
                    "end_week": 19,
                    "week_type": 0,
                    "teacher": "孙海峰",
                    "for_class": "",
                    "address": "明理102",
                    "remark": ""
                },
                {
                    "id": 1439336,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "数字逻辑",
                    "abbr": "",
                    "week": 5,
                    "start_jie": 1,
                    "end_jie": 2,
                    "start_week": 10,
                    "end_week": 19,
                    "week_type": 0,
                    "teacher": "孙海峰",
                    "for_class": "",
                    "address": "明理102",
                    "remark": ""
                },
                {
                    "id": 1439333,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "智能精准开采概论",
                    "abbr": "",
                    "week": 1,
                    "start_jie": 10,
                    "end_jie": 11,
                    "start_week": 10,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "何祥",
                    "for_class": "",
                    "address": "明理北103",
                    "remark": ""
                },
                {
                    "id": 1439343,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 11,
                    "end_week": 11,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439332,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "模拟电子技术",
                    "abbr": "",
                    "week": 2,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 11,
                    "end_week": 20,
                    "week_type": 0,
                    "teacher": "甘福宝",
                    "for_class": "",
                    "address": "天工南214",
                    "remark": ""
                },
                {
                    "id": 1439334,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "面向对象软件设计",
                    "abbr": "",
                    "week": 4,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 11,
                    "end_week": 18,
                    "week_type": 0,
                    "teacher": "潘丰",
                    "for_class": "",
                    "address": "天工南212",
                    "remark": ""
                },
                {
                    "id": 1439331,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "模拟电子技术",
                    "abbr": "",
                    "week": 4,
                    "start_jie": 7,
                    "end_jie": 8,
                    "start_week": 11,
                    "end_week": 20,
                    "week_type": 0,
                    "teacher": "甘福宝",
                    "for_class": "",
                    "address": "天工南214",
                    "remark": ""
                },
                {
                    "id": 1439335,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "面向对象软件设计",
                    "abbr": "",
                    "week": 1,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 11,
                    "end_week": 18,
                    "week_type": 0,
                    "teacher": "潘丰",
                    "for_class": "",
                    "address": "天工南204",
                    "remark": ""
                },
                {
                    "id": 1439326,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "概率论与数理统计",
                    "abbr": "",
                    "week": 2,
                    "start_jie": 7,
                    "end_jie": 8,
                    "start_week": 13,
                    "end_week": 20,
                    "week_type": 0,
                    "teacher": "倪晋波",
                    "for_class": "",
                    "address": "明理103",
                    "remark": ""
                },
                {
                    "id": 1439344,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "毛泽东思想和中国特色社会主义理论体系概论",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 13,
                    "end_week": 13,
                    "week_type": 0,
                    "teacher": "祁庆永",
                    "for_class": "",
                    "address": "天工203",
                    "remark": ""
                },
                {
                    "id": 1439325,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "概率论与数理统计",
                    "abbr": "",
                    "week": 3,
                    "start_jie": 7,
                    "end_jie": 8,
                    "start_week": 13,
                    "end_week": 20,
                    "week_type": 0,
                    "teacher": "倪晋波",
                    "for_class": "",
                    "address": "明理103",
                    "remark": ""
                },
                {
                    "id": 1439324,
                    "user_id": 268561,
                    "class_years": "大二",
                    "xn": "2023-2024",
                    "xq": 1,
                    "source": 0,
                    "course_name": "概率论与数理统计",
                    "abbr": "",
                    "week": 5,
                    "start_jie": 5,
                    "end_jie": 6,
                    "start_week": 13,
                    "end_week": 20,
                    "week_type": 0,
                    "teacher": "倪晋波",
                    "for_class": "",
                    "address": "明理103",
                    "remark": ""
                }
            ]
        }
        '''


    res = json.loads(data)

    course_list = res["data"]

    tables = []
    # 遍历课程列表
    for course in course_list:
        # 获取课程信息
        
        course_name = course["course_name"]
        teacher = course["teacher"]
        address = course["address"]
        start_week = course["start_week"]
        end_week = course["end_week"]
        start_jie = course["start_jie"]
        end_jie = course["end_jie"]
        week = course["week"]
        if(start_week<=13<=end_week and week==3):
            mdict={
                'course_name': course_name,
                'teacher' : teacher,
                'address' : address,
                'start_jie' : start_jie,
                'end_jie' : end_jie,
                'week' : week,
                'start_week' : start_week,
                'end_week' : end_week
            }
            tables.append(mdict)

    sorted_tables = sorted(tables,key=lambda d:d['start_jie'])
    content = ''
    for table in sorted_tables:
        if(table['start_week']<=13<=table['end_week'] and table['week']==3):
            # 打印课程信息
            content+= table['course_name']+"\n"
            content+= table['teacher']+'\n'
            content+= table['address']+'\n'
            content+= str(table['start_jie'])+" "+str(table['end_jie'])+"节"
            content+= '\n\n'

    fina_res = json.dumps(content,ensure_ascii=False)
    return fina_res
